name: quandoo
description: Restaurant browser
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.13.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.3
  intl: ^0.17.0
  freezed_annotation: ^0.14.2
  logger: ^1.0.0
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  retrofit: any
  dio: '>=4.0.0 <5.0.0'
  pretty_dio_logger: ^1.2.0-beta-1
  flutter_svg: ^0.22.0
  routemaster: ^0.9.5
  loadmore: ^2.0.1
  image_cacheing: ^0.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.4
  build_runner: ^2.0.6
  very_good_analysis: ^2.1.2
  injectable_generator: any
  freezed: ^0.14.2
  import_sorter: ^4.6.0
  effective_dart: ^1.3.2
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  retrofit_generator: any
  mockingjay: ^0.1.0
flutter:
  uses-material-design: true
